# Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Prepare data for GRPO training by running NeMo-Gym's ng_prepare_data.

ng_prepare_data stamps each JSONL record with an ``agent_ref`` field that
tells NeMo-Gym which agent server to route the example to during training.

This stage generates an agent-config overlay YAML from the ``agents`` list
in the workflow YAML, writes it to ``{output_dir}/agent_config_overlay.yaml``,
and passes it as the last entry in ``+config_paths``.  Supports multiple
agents (one per NeMo-Gym environment).
"""

from typing import Any

import yaml

from nvflow.core import BaseStage, StageRegistry, console
from nvflow.lib.rl.helpers import resolve_host_path


@StageRegistry.register(recipe="finance", workflow="grpo", stage="prepare_data")
class PrepareDataForGRPOStage(BaseStage):
    """Run ng_prepare_data to add agent_ref routing fields to JSONL data.

    CPU-only stage (no GPU needed).  Supports one or more agents (each
    mapping to a NeMo-Gym environment).

    Execution flow:
      1. Build an agent-config overlay from the ``agents`` list in the
         workflow YAML and write it to {output_dir}/agent_config_overlay.yaml.
      2. Submit a Slurm job that runs ``ng_prepare_data`` with the overlay
         appended to ``+config_paths``.
    """

    # -- helpers --------------------------------------------------------------

    @staticmethod
    def _build_overlay(agents: list[dict[str, Any]]) -> dict:
        """Build a NeMo-Gym agent-config overlay from the agents list.

        Each agent produces one top-level key in the overlay, keyed by its
        ``name``.  The ``agent_type`` field (default: ``simple_agent``)
        controls the NeMo-Gym agent class used.
        """
        overlay: dict = {}
        for agent_cfg in agents:
            agent_type = agent_cfg.get("agent_type", "simple_agent")
            overlay[agent_cfg["name"]] = {
                "responses_api_agents": {
                    agent_type: {
                        "entrypoint": agent_cfg.get("entrypoint", "app.py"),
                        "resources_server": agent_cfg["resources_server"],
                        "model_server": agent_cfg["model_server"],
                        "datasets": agent_cfg["datasets"],
                    }
                }
            }
        return overlay

    def _write_overlay(self, output_dir: str, agents: list[dict[str, Any]]) -> str:
        """Write the overlay YAML and return its **container** path."""
        overlay = self._build_overlay(agents)

        host_dir = resolve_host_path(output_dir)
        host_dir.mkdir(parents=True, exist_ok=True)
        overlay_path = host_dir / "agent_config_overlay.yaml"

        agent_names = [a["name"] for a in agents]
        header = "# Auto-generated by PrepareDataForGRPOStage.\n" f"# Agents: {agent_names}\n"
        overlay_path.write_text(
            header + yaml.dump(overlay, default_flow_style=False, sort_keys=False)
        )
        console.detail("Overlay written to", str(overlay_path))

        return f"{output_dir}/agent_config_overlay.yaml"

    # -- main entry points ----------------------------------------------------

    def execute(
        self,
        config: dict[str, Any],
        cluster: str,
        expname: str,
        run_after: list[str] | None = None,
    ) -> None:
        """Submit the ng_prepare_data Slurm job."""
        from nemo_skills.pipeline.cli import run_cmd, wrap_arguments

        output_dir = config["output_dir"]
        gym_path = config["gym_path"]
        container = config["container"]
        installation_command = config.get("installation_command")
        mode = config.get("mode", "train_preparation")
        should_download = config.get("should_download", False)
        agents = config["agents"]

        # 1. Generate the overlay and append it to config_paths.
        config_paths = list(config["nemo_gym_config_paths"])
        overlay_path = self._write_overlay(output_dir, agents)
        config_paths.append(overlay_path)

        # 2. Build the ng_prepare_data command.
        #    cd into the Gym directory so relative config paths resolve correctly.
        #    +error_on_almost_servers=false works around a gitlab_identifier
        #    validation bug in our local Gym version (fixed upstream).
        config_paths_str = ",".join(config_paths)
        cmd = (
            f"cd {gym_path} && "
            f'ng_prepare_data "+config_paths=[{config_paths_str}]" '
            f"+output_dirpath={output_dir} "
            f"+mode={mode} "
            f"+error_on_almost_servers=false"
        )
        if should_download:
            cmd += " +should_download=true"
        extra_args = config.get("extra_args", "")
        if extra_args:
            cmd += f" {extra_args}"

        # 3. Display summary and submit.
        console.status("Preparing data for GRPO training (ng_prepare_data)")
        console.detail("Mode", mode)
        for agent in agents:
            all_datasets = ", ".join(d["name"] for d in agent["datasets"])
            console.detail(f"Agent [{agent.get('agent_type', 'simple_agent')}]", agent["name"])
            console.detail("  Datasets", all_datasets)
        console.detail("Output", output_dir)
        console.detail("Command", cmd)
        console.blank()

        run_cmd(
            ctx=wrap_arguments(cmd),
            cluster=cluster,
            container=container,
            num_gpus=0,
            log_dir=f"{output_dir}/logs",
            expname=expname,
            run_after=run_after,
            installation_command=installation_command,
        )
        console.success(f"Data preparation job submitted → {output_dir}/")

    def validate_config(self, config: dict[str, Any]) -> None:
        """Check that all required fields are present."""
        for field in ("output_dir", "gym_path", "container", "nemo_gym_config_paths"):
            if not config.get(field):
                raise ValueError(f"'{field}' is required in prepare_data config")

        agents = config.get("agents")
        if not isinstance(agents, list) or not agents:
            raise ValueError("'agents' must be a non-empty list in prepare_data config")

        for idx, agent in enumerate(agents):
            prefix = f"agents[{idx}]"
            for field in ("name", "resources_server", "model_server", "datasets"):
                if field not in agent:
                    raise ValueError(f"'{prefix}.{field}' is required")

            if not isinstance(agent.get("datasets"), list) or not agent["datasets"]:
                raise ValueError(f"'{prefix}.datasets' must be a non-empty list")

            for i, ds in enumerate(agent["datasets"]):
                for field in ("name", "type", "jsonl_fpath"):
                    if field not in ds:
                        raise ValueError(f"'{prefix}.datasets[{i}].{field}' is required")

        mode = config.get("mode", "train_preparation")
        if mode not in ("train_preparation", "example_validation"):
            raise ValueError(
                f"'mode' must be 'train_preparation' or 'example_validation', got: {mode}"
            )
